### ISSUE TITLE
Scripted builder should have gui with embedded javac compiler

### ISSUE THREAD

**Issue by DSheirer** [DSheirer/jmbe#1]
Provide an application user interface that can download, compile and copy the JMBE library to a designated location to make it easier on the user to create the JMBE library.

**Comment by DSheirer** [comment]
The builder should be capable of running in the user's provided JRE.

**Comment by memtech3** [comment]
you could try this for windows 
https://technet.microsoft.com/en-us/library/ee692768.aspx

**Comment by DSheirer** [comment]
Closing this issue.
