### ISSUE TITLE
gradle-wrapper.properties updated for JAVA 11

### ISSUE THREAD

**Issue by CRPerryJr** [DSheirer/jmbe#11]
Error during windows compile "Could not determine java version from '11'.

With java 11, it works editing (gradle/wrapper/gradle-wrapper.properties):
distributionUrl=https://services.gradle.org/distributions/gradle-4.10.2-all.zip

**Comment by DSheirer** [comment]
Master branch was updated to use gradle 6.0 to resolve this issue.
