### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by xscode** [DSheirer/jmbe#13]
Tried compiling on both Ununtu 18.10 and Windows 10 with same error on both

`Downloading https://services.gradle.org/distributions/gradle-5.1.1-bin.zip
.................................................................................
Unzipping C:\Users\Stuart\.gradle\wrapper\dists\gradle-5.1.1-bin\90y9l8txxfw1s2o6ctiqeruwn\gradle-5.1.1-bin.zip to C:\Users\Stuart\.gradle\wrapper\dists\gradle-5.1.1-bin\90y9l8txxfw1s2o6ctiqeruwn

Welcome to Gradle 5.1.1!

Here are the highlights of this release:
 - Control which dependencies can be retrieved from which repositories
 - Production-ready configuration avoidance APIs

For more details see https://docs.gradle.org/5.1.1/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)

> Configure project :
Your finished JMBE library is here: C:\Users\Stuart\Desktop\jmbe-master\build/libs

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\Stuart\Desktop\jmbe-master\build.gradle' line: 69

* What went wrong:
A problem occurred evaluating root project 'jmbe'.
> Cannot add task 'wrapper' as a task with that name already exists.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org`

**Comment by xscode** [comment]
Thanks bigmoe1980, that fixed it!

**Comment by DSheirer** [comment]
Master branch is updated to gradle 6.0 and compatible with Java up through version 13.  Closing this issue.
