### ISSUE TITLE
p25 data dump to hdd

### ISSUE THREAD

**Issue by eeprommemory** [DSheirer/jmbe#14]
can you make it dump all data to hard drive to play back later.
something like "IdTimeDate.p25 preserving all the data transmitted.

**Comment by DSheirer** [comment]
There's already a feature in sdrtrunk that allows you to record the raw bit stream of each decoded channel to a file.  I've added a feature to record just the JMBE audio frames under this issue: https://github.com/DSheirer/sdrtrunk/issues/296 and this will be merged into the sdrtrunk master branch in the near future.

If you'd like to discuss your specific needs in more detail, you can create a new topic in the support group https://groups.google.com/forum/#!forum/sdrtrunk

Closing this issue.
