### ISSUE TITLE
Build issue: Gradle <5.0 does not support Open JDK 11 or greater

### ISSUE THREAD

**Issue by dStruct** [DSheirer/jmbe#16]
Hello,

I was having some issues compiling JMBE on various linux systems including a Raspberry Pi running Ubuntu 18.04.2 LTS (64-bit/aarch64), using Open JDK 11.0.2.

The dreaded:

```
* What went wrong:
Could not determine java version from '11.0.4'.
```

After doing some digging, I found out Gradle v4.x (what JMBE's wrapper is built with) doesn't support Open JDK 11.x.  So I simply modified the build.gradle as follows.  (Not pretty)

```
5c5,6
< sourceCompatibility = 1.8
---
> //sourceCompatibility = 1.8
> sourceCompatibility = '11'
69,70c70,71
< task wrapper(type: Wrapper) {
<     gradleVersion = '4.3.1'
---
> task wrapper1(type: Wrapper) {
>     gradleVersion = '5.0'

```
And then modified jmbe-0.3.3b/gradle/wrapper/gradle-wrapper.properties.

```
5c5
< distributionUrl=https\://services.gradle.org/distributions/gradle-4.4-bin.zip
---
> distributionUrl=https\://services.gradle.org/distributions/gradle-5.0-bin.zip

```
These changes allowed me to build JMBE without any issues on Ubuntu 18.04.2 LTS Server (64-bit/aarch64) running on a Raspberry Pi 3b+, as well as Ubuntu 18.04.2 LTS on x86_64.

> Raspberry Pi: Linux RPI 4.15.0-1041-raspi2 #44-Ubuntu SMP PREEMPT Wed Jul 3 15:45:20 UTC 2019 aarch64 aarch64 aarch64 GNU/Linux

> Laptop: Linux Laptop 4.15.0-46-generic #49-Ubuntu SMP Wed Feb 6 09:33:07 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

I hope this is helpful to someone, and thanks for SDRtrunk!

**Comment by IbleedDialTone** [comment]
worked on Win10 and Ubuntu 18.04.2 LTS for me as well. Thanks dStruct

**Comment by DdraigX** [comment]
Looks like this is an issue again. I am now on getting the error on version 13. Attempted the steps above with the latest version gradle 5.6.2 but it still is giving me a build error.

**Comment by DSheirer** [comment]
I've updated master to use gradle 6.0 which is compatible with all java versions through 13.
