### ISSUE TITLE
JMBE audio library path is NOT SET in your User Preferences

### ISSUE THREAD

**Issue by DanielAbsi** [DSheirer/jmbe#18]
Hi, I am getting this error while running SDR Trunk. I am also getting this error: JMBE audio conversion library NOT FOUND. What do these error mean and how can I repair these errors? I put the jmbe file in the same folder of sdr trunk.

**Comment by DSheirer** [comment]
Start the application.  From the Edit menu choose Preferences.  In the preferences editor, there is a section for JMBE audio.  Click on the button and select the JMBE library location.  

This sets the path/file location for the JMBE library so that the application can find it.
