### ISSUE TITLE
gradlew.bat doesn't output anything

### ISSUE THREAD

**Issue by memtech3** [DSheirer/jmbe#20]
When running gradlew.bat build I see the following message but when I look in the folder I cant find the jar file (no lib or build directory)

> Task :buildEnvironment

------------------------------------------------------------
Root project
------------------------------------------------------------

classpath
No dependencies

A web-based, searchable dependency report is available by adding the --scan option.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.0/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 1s
1 actionable task: 1 executed

**Comment by hans109h** [comment]
is there a codec directory in your build tree?  the jar might be in codec/build/lib.

**Comment by KrumbEMT** [comment]
Make sure you are using the CMD to build jmbe. Instructions are in the Readme.md (or the homepage of the project).

**Comment by DSheirer** [comment]
@memtech3 Were you able to resolve this issue?  Can we close this ticket?

**Comment by memtech3** [comment]
yes I can't remember how though I think I had to install gradle and build thatway
