### ISSUE TITLE
Compile fails on Slackware64 14.2 

### ISSUE THREAD

**Issue by jholt5638** [DSheirer/jmbe#8]
I am trying to compile jmbe-3.3a on Slackware64 14.2 I have installed the jdk 8 from oracle I have the $JAVA_HOME set properly I can build jmbe-3.2 without problems but trying 3.3a or the git master get the following output from gradle.

> Task :compileJava FAILED
/root/jmbe/src/main/java/jmbe/converters/imbe/IMBEAudioConverter.java:26: error: package jmbe.iface does not exist
import jmbe.iface.AudioConverter;
                 ^
/root/jmbe/src/main/java/jmbe/converters/imbe/IMBEAudioConverter.java:31: error: cannot find symbol
public class IMBEAudioConverter implements AudioConverter
                                           ^
  symbol: class AudioConverter
/root/jmbe/src/main/java/jmbe/JMBEAudioLibrary.java:7: error: package jmbe.iface does not exist
import jmbe.iface.AudioConversionLibrary;
                 ^
/root/jmbe/src/main/java/jmbe/JMBEAudioLibrary.java:8: error: package jmbe.iface does not exist
import jmbe.iface.AudioConverter;
                 ^
/root/jmbe/src/main/java/jmbe/JMBEAudioLibrary.java:10: error: cannot find symbol
public class JMBEAudioLibrary implements AudioConversionLibrary
                                         ^
  symbol: class AudioConversionLibrary
/root/jmbe/src/main/java/jmbe/JMBEAudioLibrary.java:59: error: cannot find symbol
    public AudioConverter getAudioConverter(String codec, AudioFormat output)
           ^
  symbol:   class AudioConverter
  location: class JMBEAudioLibrary
/root/jmbe/src/main/java/jmbe/converters/imbe/IMBEAudioConverter.java:79: error: method does not override or implement a method from a supertype
    @Override
    ^
/root/jmbe/src/main/java/jmbe/converters/imbe/IMBEAudioConverter.java:93: error: method does not override or implement a method from a supertype
    @Override
    ^
/root/jmbe/src/main/java/jmbe/converters/imbe/IMBEAudioConverter.java:99: error: method does not override or implement a method from a supertype
    @Override
    ^
/root/jmbe/src/main/java/jmbe/JMBEAudioLibrary.java:12: error: method does not override or implement a method from a supertype
    @Override
    ^
/root/jmbe/src/main/java/jmbe/JMBEAudioLibrary.java:27: error: method does not override or implement a method from a supertype
    @Override
    ^
/root/jmbe/src/main/java/jmbe/JMBEAudioLibrary.java:34: error: method does not override or implement a method from a supertype
    @Override
    ^
/root/jmbe/src/main/java/jmbe/JMBEAudioLibrary.java:40: error: method does not override or implement a method from a supertype
    @Override
    ^
/root/jmbe/src/main/java/jmbe/JMBEAudioLibrary.java:46: error: method does not override or implement a method from a supertype
    @Override
    ^
/root/jmbe/src/main/java/jmbe/JMBEAudioLibrary.java:58: error: method does not override or implement a method from a supertype
    @Override
    ^
15 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
1 actionable task: 1 executed
I have tried using both the gradle wrapper included and installing gradle directly both produce the same result

**Comment by DSheirer** [comment]
This should be resolved with the 0.3.3b release.  Please download the latest release and follow the same instructions.

**Comment by jholt5638** [comment]
problem is resolved with the 0.3.3b release thanks for the quick resolution
